
[env:T-Display]
;Puce ESP32-DOWD Q6
;Memoire 25Q128JVSQ 
;CH9102F
;Devalider SMOOTH

platform = espressif32
board = ttgo-lora32-v1
board_build.partitions = partitions_custom.csv


framework = arduino
;upload_protocol = esptool

monitor_speed = 115200

lib_deps = 
	Wire
	SPI
	
upload_protocol = espota
upload_port = 192.168.0.48
;upload_port = esp32-blesensor.local

lib_extra_dirs =
	D:\PlatformIO\libraries\
    ;~\Documents\PlatformIO\Libraries
